# Site settings
title: Machine Learning and Adaptive Intelligence 2013
author:
  name: Neil D. Lawrence
  email: 
description: > # this means to ignore newlines until "baseurl:"
  Module on machine learning and Adaptive Intelligence as taught in 2013.
baseurl: "/mlai2013/" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com/" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

ghub:
  edit: true
  repository: mlai2013

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: ndltalk


analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
